services:
  - name: keruj-backup-postgres-s3
    type: cron
    schedule: "0 3 * * *"
    region: frankfurt
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AWS_ENDPOINT_URL_S3
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: POSTGRES_VERSION
        sync: false

